# Generated by Django 4.1.13 on 2023-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
